### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by dynnamitt** [Comcast/MirrorTool-for-Kafka-Connect#15]
Hi,

I did not manage to install this addon. 
My connect is installed from confluent-kafka-2.11 (confluent 5.1)
I have 2 more external addons that works fine but this one isn't ..

```
Failed to find any class that implements Connector and which name matches com.comcast.kafka.connect.kafka.KafkaSourceConnector, available connectors are: PluginDesc{klass=class com.github.jcustenborder.kafka.connect.rabbitmq.RabbitMQSinkConnector, name='com.github.jcustenborder.kafka.connect.rabbitmq.RabbitMQSinkConnector', version='0.0.2-SNAPSHOT', encodedVersion=0.0.2-SNAPSHOT, type=sink, typeName='sink', location='file:/local/app/kafka-connect-rabbitmq/'}, 
...
```

i created a subdir called mirror-tool (right next to the other two addons that I mention that's ok)

**Comment by dynnamitt** [comment]
sorry if the above error message isn't very clear but I'm assuming this tool is installed just like
debezium : https://debezium.io/docs/install/stable/

**Comment by rhysmccaig** [comment]
Hi @dynnamitt,

Can you check in the connect startup logs where connect is trying to load plugins from?
For example, on my test confluent docker image which loads the plugin correctly, I see:

```
INFO Scanning for plugin classes. This might take a moment ... (org.apache.kafka.connect.cli.ConnectDistributed)
INFO Loading plugin from: /usr/share/java/kafka (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/java/kafka/} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
INFO Added plugin 'com.comcast.kafka.connect.kafka.KafkaSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
```

My docker image is configured to install mirror tool to: `/usr/share/java/kafka/MirrorTool-${MIRRORTOOL_VERSION}/MirrorTool-${MIRRORTOOL_VERSION}.jar`

Ive configured the plugin path as: `/usr/share/java` - you might want to check this too.

Let me know how you go

**Comment by rhysmccaig** [comment]
Closing this issue, please re-open if you continue to have issues.
