### ISSUE TITLE
kafka connect producing 4-5x more traffic than consume traffic

### ISSUE THREAD

**Issue by Tahvok** [Comcast/MirrorTool-for-Kafka-Connect#16]
We are evaluating of replacing kafka mirror maker with this kafka connect consumer, although it's working better for us, it is for some unknown reason producing 4 times more traffic than it is consuming. Look at this metric for example:
![Screenshot_20190619_125253](https://user-images.githubusercontent.com/6513056/59755905-6c83c900-9291-11e9-845b-66e23106486e.png)

For comparison that is how the traffic looks in kafka mirror maker - and is what I would expect from kafka connect as well:
![Screenshot_20190619_125611](https://user-images.githubusercontent.com/6513056/59756041-aa80ed00-9291-11e9-9d5f-cbc79981c377.png)

What could be producing all this traffic?

**Comment by albertpx** [comment]
The issue was that compression type was not set for producer.
After setting `producer.compression.type=snappy` in `worker.properties` the traffic dropped

**Comment by Tahvok** [comment]
The issue was that compression type was not set for producer.
After setting `producer.compression.type=snappy` in `worker.properties` the traffic dropped

**Comment by rhysmccaig** [comment]
@Tahvok Thanks for sharing the solution! I'm glad it worked out!

Maybe relevant for you evaluation - In an upcoming Kafka release, MirrorMaker 2.0 will be released which will implement all the features of this connector, and more, as it will be implemented as a Connector _and_ a command line tool. 
See here for more details: https://cwiki.apache.org/confluence/display/KAFKA/KIP-382%3A+MirrorMaker+2.0
