### ISSUE TITLE
Where to mention Destination Zookeeper broker address?

### ISSUE THREAD

**Issue by vishnu2497** [Comcast/MirrorTool-for-Kafka-Connect#25]
Hi,

In the Configuration properties there is option called source.bootstrap.servers to mention the source broker.

where i need to mention the destination bootstrap servers?

i am using Apache Kafka and paste jar file in libs folder and while starting file i dint know where to mention those properties?

**Comment by rhysmccaig** [comment]
Hi @vishnu2497. This plugin is intended to be used by a [Kafka Connect ](https://kafka.apache.org/documentation/#connect) cluster that is already set up to run against the destination cluster. As such there is no configuration option in this plugin to specify destination cluster.
