### ISSUE TITLE
Exactly once semantic support

### ISSUE THREAD

**Issue by RoboBuffalo** [Comcast/MirrorTool-for-Kafka-Connect#26]
Hi there,
Is MirrorTool supports transactions with Exactly once semantic?

**Comment by rhysmccaig** [comment]
Hi @RoboBuffalo, it doesn't, but I believe it is a feature planned for a future release of [MirrorMaker2](https://blog.cloudera.com/a-look-inside-kafka-mirrormaker-2/)
