### ISSUE TITLE
Compatibility with InsertField transforms?

### ISSUE THREAD

**Issue by m4nuC** [Comcast/MirrorTool-for-Kafka-Connect#27]
Hi,

I have been trying to apply an InsertSource transform to the data point before passing it on to the target topic. This fails with an error along the lines:

`InsertField can not be used on Byte array types`

If I remove the converter, then the insertion works but the initial data is not being converted.

Can you see any way around this?

My connector config look like this:

```
name=testing_mirror
connector.class=com.comcast.kafka.connect.kafka.KafkaSourceConnector
source.group.id=tersting_group
source.topic.whitelist=time_data
tasks.max=1
transforms=InsertSource
transforms.InsertSource.type=org.apache.kafka.connect.transforms.InsertField$Value
transforms.InsertSource.static.field=test_insert
transforms.InsertSource.static.value=test_insert
source.bootstrap.servers=kakfa:9092
key.converter.schemas.enable=false
value.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
key.converter=org.apache.kafka.connect.converters.ByteArrayConverter

```

**Comment by mccaig** [comment]
Hi @m4nuC - Unfortunately I don't have time to look into this at the moment (probably until the end of 2020). 
If you have a relatively recent Kafka Connect cluster - you should check out mirrormarker2 which has been shipping since kafka 2.4, as this has much better test coverage and hopefully will resolve this issue for you: https://cwiki.apache.org/confluence/display/KAFKA/KIP-382%3A+MirrorMaker+2.0

**Comment by m4nuC** [comment]
Thanks, @mccaig I did and very much stuck there as well. Do you think there is a way to modify MirrorTool-for-Kafka-Connect to enable doing something like deserializing -> transform -> reserializing before proxying the records?

**Comment by mccaig** [comment]
I think the solution here would be to use a value converter that matches your data type. Assuming your messages are in JSON format, then `org.apache.kafka.connect.json.JsonConverter` should do the trick.
